services:
  openobserve:
    image: openobserve/openobserve:latest
    hostname: openobserve
    container_name: openobserve
    # ports:
    #   - "5080:5080"
    volumes:
      - openobserve_data:/data
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - dokploy-network

  vector:
    image: timberio/vector:0.41.1-alpine
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./vector.yaml:/etc/vector/vector.yaml:ro
    depends_on:
      - openobserve
    restart: unless-stopped
    networks:
      - dokploy-network

volumes:
  openobserve_data:
