services:
  openobserve:
    image: openobserve/openobserve:latest
    hostname: openobserve
    # ports:
    #   - "5080:5080"
    volumes:
      - openobserve_data:/data
    restart: unless-stopped
    env_file:
      - .env

  vector:
    image: timberio/vector:0.41.1-alpine
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./vector.toml:/etc/vector/vector.yaml:ro
    depends_on:
      - openobserve
    restart: unless-stopped

volumes:
  openobserve_data:
