[sources.docker]
type = "docker_logs"

[sinks.openobserve]
type = "http"
inputs = [ source or transform id ]
uri = "https://logger.sitedev.es/api/default/default/_json"
method = "post"
auth.strategy = "basic"
auth.user = "root@example.com"
auth.password = "1Ym2xdivsfvQ1hJr"
compression = "gzip"
encoding.codec = "json"
encoding.timestamp_format = "rfc3339"
healthcheck.enabled = false
