[sources.docker]
type = "docker_logs"

[sinks.openobserve]
type = "http"
inputs = ["docker"]
uri = "http://openobserve:5080/api/default/docker/_json"
method = "post"

[sinks.openobserve.auth]
strategy = "basic"
user = "root@example.com"
password = "supersecret"

[sinks.openobserve.encoding]
codec = "json"

[sinks.openobserve.compression]
type = "gzip"

[sinks.openobserve.healthcheck]
enabled = true
uri = "http://openobserve:5080/healthz"
